version: '3.4'

services:
  database:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
  messagecase.api:
    image: ${DOCKER_REGISTRY-}messagecaseapi
    build:
      context: .
      dockerfile: MessageCase.API/Dockerfile
    depends_on:
      - database
